### ISSUE TITLE
ヘルプ表示時にカレンダーで遷移すると表示が崩れる

### ISSUE THREAD

**Issue by igrs** [team-315/better-day#85]
再現方法
1．メニューからhelpを選択
2．helpのレイヤーが表示された状態で、日付部分をクリックし、カレンダーで適当な日付を選択
3．該当の日付が表示されhelpのレイヤーの表示が狂う。
ブラウザ：Chrome

**Comment by katsuhide** [comment]
とりあえず直した。
pageguide.jsのバグなのかわからんが、日付変更後にヘルプを表示できなくなるけどまあいいや。
